acts_as_archive:
  rake: >=0.8.7
  rspec: ~>1.0
  default:
    activesupport: =3.0.3
    active_wrapper-solo: =0.4.1
    also_migrate: =0.2.1
    externals: =1.0.2
    framework_fixture: =0.1.2
    mover: =0.3.3
    rack-test: =0.5.6